#if !defined(ARRAYS_TEMPERATURE_H)
#define ARRAYS_TEMPERATURE_H
/* This file is automatically generated by define_array.py */

/* temp (double, 2D) [0:itot+1] x [0:jsize+1] */
#define TEMP_MIN_I (0)
#define TEMP_MAX_I (itot+1)
#define TEMP_LEN_I (TEMP_MAX_I-TEMP_MIN_I+1)
#define TEMP_MIN_J (0)
#define TEMP_MAX_J (jsize+1)
#define TEMP_LEN_J (TEMP_MAX_J-TEMP_MIN_J+1)
#define TEMP_MEMSIZE (sizeof(double)*(TEMP_LEN_I)*(TEMP_LEN_J))
#define TEMP(I, J) (temp[(J)*(itot+2)+(I)])

/* tempforcex (double, 2D) [2:itot] x [1:jsize] */
#define TEMPFORCEX_MIN_I (2)
#define TEMPFORCEX_MAX_I (itot)
#define TEMPFORCEX_LEN_I (TEMPFORCEX_MAX_I-TEMPFORCEX_MIN_I+1)
#define TEMPFORCEX_MIN_J (1)
#define TEMPFORCEX_MAX_J (jsize)
#define TEMPFORCEX_LEN_J (TEMPFORCEX_MAX_J-TEMPFORCEX_MIN_J+1)
#define TEMPFORCEX_MEMSIZE (sizeof(double)*(TEMPFORCEX_LEN_I)*(TEMPFORCEX_LEN_J))
#define TEMPFORCEX(I, J) (tempforcex[((J)-1)*(itot-1)+((I)-2)])

/* srctempa (double, 2D) [1:itot] x [1:jsize] */
#define SRCTEMPA_MIN_I (1)
#define SRCTEMPA_MAX_I (itot)
#define SRCTEMPA_LEN_I (SRCTEMPA_MAX_I-SRCTEMPA_MIN_I+1)
#define SRCTEMPA_MIN_J (1)
#define SRCTEMPA_MAX_J (jsize)
#define SRCTEMPA_LEN_J (SRCTEMPA_MAX_J-SRCTEMPA_MIN_J+1)
#define SRCTEMPA_MEMSIZE (sizeof(double)*(SRCTEMPA_LEN_I)*(SRCTEMPA_LEN_J))
#define SRCTEMPA(I, J) (srctempa[((J)-1)*(itot  )+((I)-1)])

/* srctempb (double, 2D) [1:itot] x [1:jsize] */
#define SRCTEMPB_MIN_I (1)
#define SRCTEMPB_MAX_I (itot)
#define SRCTEMPB_LEN_I (SRCTEMPB_MAX_I-SRCTEMPB_MIN_I+1)
#define SRCTEMPB_MIN_J (1)
#define SRCTEMPB_MAX_J (jsize)
#define SRCTEMPB_LEN_J (SRCTEMPB_MAX_J-SRCTEMPB_MIN_J+1)
#define SRCTEMPB_MEMSIZE (sizeof(double)*(SRCTEMPB_LEN_I)*(SRCTEMPB_LEN_J))
#define SRCTEMPB(I, J) (srctempb[((J)-1)*(itot  )+((I)-1)])

/* srctempg (double, 2D) [1:itot] x [1:jsize] */
#define SRCTEMPG_MIN_I (1)
#define SRCTEMPG_MAX_I (itot)
#define SRCTEMPG_LEN_I (SRCTEMPG_MAX_I-SRCTEMPG_MIN_I+1)
#define SRCTEMPG_MIN_J (1)
#define SRCTEMPG_MAX_J (jsize)
#define SRCTEMPG_LEN_J (SRCTEMPG_MAX_J-SRCTEMPG_MIN_J+1)
#define SRCTEMPG_MEMSIZE (sizeof(double)*(SRCTEMPG_LEN_I)*(SRCTEMPG_LEN_J))
#define SRCTEMPG(I, J) (srctempg[((J)-1)*(itot  )+((I)-1)])

#endif // ARRAYS_TEMPERATURE_H
